name: ag_news
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- pyspark
- pytorch
- numpy
- pandas
- scipy
- scikit-learn
- polars
- orjson
- pyarrow=12.0.1
- awswrangler
- transformers
- accelerate
- duckdb
- s3fs
- nomkl
- umap-learn
- smart-open
- onnxruntime
- spacy
- seqeval
- gensim
- numba
- sqlalchemy
- pytest
- pip
- pip:
  - datasets===2.19.1
  - huggingface-hub
  - fsspec==2023.9.2
  - neo4j
