data:
  dataset_name: "sh0416/ag_news"
  output_path: "file:///C:/AGNewsProcessor/Output"
  huggingface_token: "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"

spark:
  app_name: "AGNewsProcessor"
  master: "local[*]"
  memory: "4g"
