name: Docker Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t agnews -f Dockerfile .

    - name: Save Docker image
      uses: actions/upload-artifact@v3
      with:
        name: ag-news-processor
        path: /tmp/agnews.tar
